/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is prov`ided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ADC_multi_DIV.h"
#include "UART_char.h"


char tx_buf[50];
int main()
{

	RCC_Init();
	//RCC_USART_Init();
	GPIOA_Init();
	GPIOA_USART_Init();
	USART_Init();
	ADC_CH1_CH2_Init();

	while (1){
	//Read_ADC_Data(); inside ISR
	uint16_t p_data = pot_pop_data (&pot_buf);
	ADC_CR2 |= (1 << 30);

	uint16_t s_data = sensor_pop_data (&sensor_buf);
	ADC_CR2 |= (1 << 30);

	sprintf(tx_buf,"potentiometer_data: %d\r\n",p_data);
	sprintf(tx_buf,"sensor_data: %d\r\n",s_data);
	}
	return 0;
}
